Warnings for deterministic ordering
dotnet/EntityFramework.Docs pull request #3685
Opened 2022-01-19 11:42 UTC by roji

In split query, and also a stronger note in the pagination page.

Closes #3242

2022-01-23 09:50 UTC, ajcvickers approved these changes

2022-01-24 18:40 UTC, smitpatel requested changes
There is no issue of deterministic ordering.

2022-01-24 18:41 UTC, roji commented
@smitpatel then please propose another warning text, I don't mind.

2022-01-24 18:43 UTC, smitpatel commented
We already discussed that in teams chat.

2022-01-24 18:52 UTC, roji commented
I push [this commit](https://github.com/dotnet/EntityFramework.Docs/pull/3685/commits/2f0d6f5caa4acc9eea3233a3c9af0610b297ea9f) as a result of that discussion, believing that's what you wanted. If it isn't, just propose whatever you think is right.

2022-01-24 18:58 UTC, smitpatel commented
Pagination queries without explicit ordering causes non-deterministic result set is right. (though non-pagination page should mention pagination, we discussed that pagination doesn't required to mentioned on the page which talks about pagination). But the main issue remains, there is no non-deterministic ordering, there is only non-deterministic result set.

If you want me to update the message, just assign the issue to me. I will get around to it at some point.

2022-01-24 19:03 UTC, roji commented
> But the main issue remains, there is no non-deterministic ordering, there is only non-deterministic result set.

I don't see it that way: a query whose orderings can produce different resultsets (because of lack of a unique column) can be said to have non-deterministic ordering.

But I'll close this and let you deal with this whichever way you want.

2022-01-27 13:17 UTC, ajcvickers commented on entity-framework/core/querying/pagination.md
> +> Regardless of the pagination method used, always make sure that your ordering is fully deterministic. For example, if results are ordered only by date, but there can be multiple results with the sa
```suggestion
> Regardless of the pagination method used, always make sure that your ordering is fully unique. For example, if results are ordered only by date, but there can be multiple results with the same date, then results could be skipped when paginating as they're ordered differently across two paginating queries. Ordering by both date and ID (or any other unique property or combination of properties) makes the ordering fully unique and avoids this problem. Note that relational databases do not apply any ordering by default, even on the primary key.
```

2022-01-27 13:18 UTC, ajcvickers commented on entity-framework/core/querying/single-split-queries.md
> +> When using split queries with Skip/Take, pay special attention to making your query ordering fully deterministic; not doing so could cause incorrect data to be returned. For example, if results are
```suggestion
> When using split queries with Skip/Take, pay special attention to making your query ordering fully unique; not doing so could cause incorrect data to be returned. For example, if results are ordered only by date, but there can be multiple results with the same date, then each one of the split queries could each get different results from the database. Ordering by both date and ID (or any other unique property or combination of properties) makes the ordering fully unique and avoids this problem. Note that relational databases do not apply any ordering by default, even on the primary key.
```

2022-01-28 21:39 UTC, ajcvickers approved these changes

2022-01-31 10:58 UTC, ajcvickers commented
@smitpatel Can you sign off on this so I can merge?

2022-01-31 18:39 UTC, smitpatel approved these changes

2022-01-31 18:46 UTC, merged