Document TPC
dotnet/EntityFramework.Docs pull request #4080
Opened 2022-10-11 21:08 UTC by AndriySvyryd

Fixes #3764

2022-10-12 15:52 UTC, roji requested changes

2022-10-12 17:27 UTC, AndriySvyryd commented on entity-framework/core/modeling/inheritance.md
> +## Foreign key constraints
Sure, I can add a similar sub-section to TPT

2022-10-12 17:30 UTC, AndriySvyryd commented on entity-framework/core/modeling/inheritance.md
> +> Instead of calling `ToTable` on each entity type you can call `modelBuilder.Entity<Blog>().UseTptMappingStrategy()` on each root entity type and the table names will be generated by EF.
Since we say that TPT should only be used with existing databases I think that the `ToTable` way will be more common.

2022-10-12 17:32 UTC, AndriySvyryd commented on entity-framework/core/modeling/inheritance.md
> +> Instead of calling `ToTable` on each entity type just calling `modelBuilder.Entity<Blog>().UseTpcMappingStrategy()` on each root entity type will generate the table names by convention.
`UseTpcMappingStrategy` needs to be called anyway, I don't think that removing the `ToTable` calls from the sample improves it.

2022-10-12 17:36 UTC, AndriySvyryd commented on entity-framework/core/modeling/inheritance.md
> +> Also see [stored computed column](xref:core/modeling/table-splitting#computed-columns)
I have no idea where this came from, it's not even a valid link

2022-10-13 09:57 UTC, roji commented on entity-framework/core/modeling/inheritance.md
> +> Instead of calling `ToTable` on each entity type you can call `modelBuilder.Entity<Blog>().UseTptMappingStrategy()` on each root entity type and the table names will be generated by EF.
We say it should, but that doesn't necessarily means that's how users use it :) I'd still say that UseTptMappingStrategy should be the default as long it works (i.e. your tables do align with the default naming), and that ToTable should only be used when that's not the case.

But am OK if you prefer to keep as-is.

2022-10-13 09:58 UTC, roji commented on entity-framework/core/modeling/inheritance.md
> +> Instead of calling `ToTable` on each entity type just calling `modelBuilder.Entity<Blog>().UseTpcMappingStrategy()` on each root entity type will generate the table names by convention.
Well it's redundant code for many uses cases - we don't have ToTable in regular, non-inheritance code samples. But anyway...

2022-10-13 09:58 UTC, roji approved these changes

2022-10-13 17:01 UTC, merged