Add the introducation to StronglyTypedId
dotnet/EntityFramework.Docs pull request #4163
Opened 2022-11-28 01:27 UTC by yangzhongke

Add the introduction to LessCode.EFCore.StronglyTypedId

As proposed on [https://github.com/dotnet/EntityFramework.Docs/issues/4160#issuecomment-1327216363](https://github.com/dotnet/EntityFramework.Docs/issues/4160#issuecomment-1327216363)

2022-11-28 06:47 UTC, ErikEJ requested changes

2022-11-28 06:47 UTC, ErikEJ commented on entity-framework/core/extensions/index.md
> +
Remove extra line

2022-11-28 06:47 UTC, ErikEJ commented on entity-framework/core/extensions/index.md
> +With this extension, developers just need to add [HasStronglyTypedId] on the entity type, all the related classes will be generated automatically at compile time.
remove this sentence, and reduce to:

A source generator that can generate strongly-typed-id classes automatically for entities. For EF Core: 7.

2022-11-28 06:47 UTC, ErikEJ commented on entity-framework/core/extensions/index.md
> +[GitHub repository]([https://github.com/R4ND3LL/EntityFrameworkRuler/](https://github.com/yangzhongke/LessCode.EFCore.StronglyTypedId))
Fix link

2022-11-29 21:41 UTC, yangzhongke commented
Thank you, I have resolved all the suggestions.
It shows 'Merging is blocked', what can I do to make it merged?

2022-11-29 22:03 UTC, yangzhongke reviewed
Done

2022-11-30 00:13 UTC, roji commented on entity-framework/core/extensions/index.md
> +
Can you please remove on of these blank lines? The markdown linter is complaining about it.

2022-11-30 01:06 UTC, closed without merging